config/routes.rb
Rails.application.routes.draw do
  resources :users
  get '/signup' => 'users#new', as: :signup
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :phone_number, presence: true, numericality: true
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    redirect_to login_path unless @current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render template: 'home'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @login_form = LoginForm.new
  end
  def create
    @login_form = LoginForm.new(login_params)
    if @login_form.valid?
      session[:user_id] = @login_form.user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  private

  def login_params
    params.require(:login_form).permit(
      :email,
      :password
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "user successfully created"
      redirect_to login_path
    else
      render 'new'
    end
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGWebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <%= render 'partials/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_flashes.html.erb
<div class="container flashes">
  <% if flash %>
    <% flash.each do |flash_type, text| %>
      <% if flash_type == 'notice'%>
        <div class='alert alert-success' role='alert'>
          <%= text %>
        </div>
      <% else %>
        <div class="alert alert-danger" role="alert">
          <%= text %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/partials/_form_errors.html.erb
<div class='container user-form'>
  <div class="alert alert-danger">
    <h4><%= pluralize(errors.count, "Error" ) %></h4>
    <ul>
      <% errors.each do |err| %>
        <li><%= err %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Rails Girls Nairobi</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Our Members</a></li>
        <li> <%= link_to 'Sign Out', logout_path %></li>
      <% else %>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Our Members</a></li>
        <li> <%= link_to 'Join Us', signup_path %></li>
        <li> <%= link_to 'Sign In', login_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/_form.html.erb
<%= form_for @user do |u| %>
  <div class='form-group'>
    <%= u.label :name %>
    <%= u.text_field :name, placeholder: 'First Last', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= u.label :email %>
    <%= u.email_field :email, placeholder: 'firstlast@email.com', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= u.label :phone_number %>
    <%= u.number_field :phone_number, placeholder: '0717000121', value:'0717000121', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= u.label :password %>
    <%= u.password_field :password, placeholder: 'Enter password', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= u.submit save_prompt, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class='container'>
  <div class='user-form'>
    <h3 class='form-header'>Sign Up</h3>
    <hr>
    <br>
    <%= form_for @user, url: { action: :create } do |f| %>
      <%= render partial: 'partials/form_errors',
          locals: { errors: @user.errors.full_messages } if @user.errors.any? %>
      <%= render partial: 'form', locals: { f:f, save_prompt: 'Create user' }%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>